apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: radarr
  namespace: media

resources:
  - resources/ingress.yaml
  - resources/config-pvc.yaml

helmCharts:
  - name: radarr
    releaseName: radarr
    repo: https://k8s-home-lab.github.io/helm-charts/
    version: 17.4.0
    valuesFile: helm/values.yaml
