apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sonarr
  namespace: media

resources:
  - resources/ingress.yaml
  - resources/config-pvc.yaml

helmCharts:
  - name: sonarr
    releaseName: sonarr
    repo: https://k8s-at-home.com/charts/
    version: 15.1.0
    valuesFile: helm/values.yaml
