apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-rwx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.5
    path: /srv/nfs/deluge
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-rwx
