apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: delugevpn
          image: binhex/arch-delugevpn:latest
          env:
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "mullvad"
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: mullvad-credentials
                  key: username
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: mullvad-credentials
                  key: password
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_CONFIG
              valueFrom:
                secretKeyRef:
                  name: mullvad-wireguard
                  key: config
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
          ports:
            - containerPort: 8112
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          size: 5Gi
          storageClass: local-path
        - name: downloads
          persistentVolumeClaim:
            claimName: media-pvc
