apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-rwx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: homelab
    path: /srv/nfs/sonarr
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-rwx
