apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jg1g
  annotations:
    #traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-dns
    #traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
       - jg1g.com
      secretName: jg1g-tls
  rules:
  - host: jg1g.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jg1g-svc
            port:
              number: 80
