apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-rwx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.70
    path: /srv/nfs/radarr
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-rwx
